### ISSUE TITLE
License should be clarified

### ISSUE THREAD

**Issue by chipotle** [papatangosierra/livejournal-archive-tools#15]
Hi. Thanks for your work on this! I've forked this repo to https://github.com/chipotle/livejournal-archive-tools and made a few changes to both scripts -- getljxml's configuration is in a YAML file, it only saves monthly files that have entries, etc., and my version of lj2dayone.rb fixes what looked like some bad regex patterns and now uses [pandoc](https://pandoc.org) for high-fidelity Markdown conversion. (I know that's another external dependency, but I discovered my own LJ had entries which needed it!)

I don't know if you'd want to make any of those changes to your own script -- I can open a PR if you want -- but the big question I have is: you don't specify a license file for this, which means that my fork is technically probably violating your copyright! Is it possible for you to add a LICENSE file or otherwise specify some kind of open source license like GPL or MIT?

**Comment by papatangosierra** [comment]
Hey! I'm extremely flattered that you took the time to make these improvements! I've licensed the scripts under the MIT license, and I'd be delighted to integrate anything you wanted to submit.
