### ISSUE TITLE
lj2dayone.rb bug?

### ISSUE THREAD

**Issue by itshouldbebroke** [papatangosierra/livejournal-archive-tools#16]
Hello! I'm new to both Github and using Terminal on my MacBook, so pardon my beginning question. I was able to follow instructions and get all the XML files downloaded (yay!) but I keep getting a bug for the lj2dayone.rb script. (Yes, I already installed Day One and opened it at least once, v5.1.) Is something not working correctly now that Day One is on v5 as opposed to the v2/v3 I think you designed this for? I'm getting an error that looks like this:

[BUG] Unexpected node test: <:child>: <[:qname, "", "subject"]> (RuntimeError)

Does this mean there's something wrong with the code that tries to pull the subject into Day One?

Grateful for any help and thanks so much for this awesome tool that let me download over ten years worth of entries tonight!

**Comment by papatangosierra** [comment]
Hey! I've looked into this and the good news is that I'm seeing the same bug, so if/when I can fix it, it should work for you, too. The bad news is, I don't have any idea how to fix it, and a quick google for the error message isn't turning up anything obvious. I'm very busy with IRL stuff at the moment, unfortunately, but I would like to get this fixed, so when I get a chance I'll try to look more deeply into the problem. Thanks for letting me know!

**Comment by itshouldbebroke** [comment]
Excellent, thank you for looking at it when you get the chance!

**Comment by papatangosierra** [comment]
Hi there! If you're still around and interested in using this script, the bug you encountered has been fixed. :)

Also, an enterprising person has created an improved version of these tools here: https://github.com/chipotle/livejournal-archive-tools

The one downside of their improved version is that they require downloading a package called Pandoc—which shouldn't be hard, but it is an extra step. Either way, you have some options now! :)

**Comment by papatangosierra** [comment]
This bug has been fixed. Thanks, Gabe. <3

**Comment by itshouldbebroke** [comment]
Yay! I'm super excited. I was able to get it to work (sort of); even though all of my XML files are downloaded already, it decided it only wanted to import 2001 and 2002's entries into Day One (v.6). In the terminal, it starting giving me this:

Entry from 2001-11-14 23:10:00 added.
CoreData: annotation: PostSaveMaintenance: fileSize 8540792 greater than prune threshold
CoreData: annotation: PostSaveMaintenance: wal_checkpoint(TRUNCATE) 
Created new entry with uuid: 6CF17515439D489B91FFBA439B5E0612

It looks like the "prune threshold" ones still ended up getting adding to Day One, actually. It ended like this -- not sure if this is a normal "end of code" sort of deal, but I found the "unconsumed characters" thing sort of weird. Dunno if that's something goofy on my part (looks like it ends with the title -- or maybe first line? -- of one of my LJ entries) or something weird with the code. Pasting below just in case it gives you an "ah ha" moment!

Entry from 2002-06-29 22:08:00 added.
CoreData: annotation: PostSaveMaintenance: fileSize 59484592 greater than prune threshold
CoreData: annotation: PostSaveMaintenance: wal_checkpoint(TRUNCATE) 
Created new entry with uuid: 9186FD83B4244492BA0DC1EE4F9C6135

Entry from 2002-06-30 10:28:00 added.
Traceback (most recent call last):
	10: from ./lj2dayone.rb:37:in `<main>'
	 9: from ./lj2dayone.rb:37:in `each'
	 8: from ./lj2dayone.rb:38:in `block in <main>'
	 7: from ./lj2dayone.rb:38:in `new'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/document.rb:45:in `initialize'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/document.rb:288:in `build'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/parsers/treeparser.rb:23:in `parse'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/parsers/baseparser.rb:183:in `pull'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/parsers/baseparser.rb:391:in `pull_event'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/source.rb:220:in `match'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/source.rb:220:in `match': invalid byte sequence in UTF-8 (ArgumentError)
	9: from ./lj2dayone.rb:37:in `<main>'
	8: from ./lj2dayone.rb:37:in `each'
	7: from ./lj2dayone.rb:38:in `block in <main>'
	6: from ./lj2dayone.rb:38:in `new'
	5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/document.rb:45:in `initialize'
	4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/document.rb:288:in `build'
	3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/parsers/treeparser.rb:23:in `parse'
	2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/parsers/baseparser.rb:183:in `pull'
	1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/parsers/baseparser.rb:332:in `pull_event'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/parsers/baseparser.rb:406:in `rescue in pull_event': #<ArgumentError: invalid byte sequence in UTF-8> (REXML::ParseException)
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/source.rb:220:in `match'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/source.rb:220:in `match'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/parsers/baseparser.rb:391:in `pull_event'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/parsers/baseparser.rb:183:in `pull'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/parsers/treeparser.rb:23:in `parse'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/document.rb:288:in `build'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rexml/document.rb:45:in `initialize'
./lj2dayone.rb:38:in `new'
./lj2dayone.rb:38:in `block in <main>'
./lj2dayone.rb:37:in `each'
./lj2dayone.rb:37:in `<main>'
...
Exception parsing
Line: 256
Position: 35393
Last 80 unconsumed characters:
this afternoon, me, mer, kelsey, and dan p went hiking up to white rock.  kelsey

**Comment by itshouldbebroke** [comment]
Update/workaround: I removed the XML files from the folder that had already successfully imported and ran lj2dayone.rb again -- and it seems to have imported all of the remaining files (although I did get more "prune threshold" stuff; still, nothing seems to have been imported incorrectly). Yay! <3
